export const initialData = {
  personalData: [
    "Avatar",
    "Name",
    "Specialty",
    "email",
    "Address",
    "PostalCode",
  ],

  profiles: [
    {
      id: 1,
      name: "Emilia do Carmo",
      specialty: "Contabilista",
      email: "emilia.docarmo@gmail.com",
      address: "casa monte 900A",
      postalCode: "8150-026",
      isAdmin: false,
      isContractor: true,
      avatar: "a",
    },
    {
      id: 2,
      name: "Ndimbulukeny Ngueve",
      specialty: "Enfermeira",
      email: "ndimbulukeny.ngueve@gmail.com",
      address: "casa monte 900B",
      postalCode: "8150-027",
      isAdmin: false,
      isContractor: true,
      avatar: "b",
    },
    {
      id: 3,
      name: " Afonso Aurelio",
      specialty: "Pedreiro",
      email: "afonso.aurelio@gmail.com",
      address: "casa monte 900C",
      postalCode: "8150-028",
      isAdmin: false,
      isContractor: true,
      avatar: "c",
    },
    {
      id: 4,
      name: " Domingala Muenho",
      specialty: "Estilista",
      email: "domingala.muenho@gmail.com",
      address: "casa monte 900D",
      postalCode: "8150-029",
      isAdmin: false,
      isContractor: true,
      avatar: "d",
    },
    {
      id: 5,
      name: " Augusto Camaty",
      specialty: "Carpinteiro",
      email: "augusto.camaty@gmail.com",
      address: "casa monte 900E",
      postalCode: "8150-030",
      isAdmin: false,
      isContractor: true,
      avatar: "e",
    },
    {
      id: 6,
      name: " Rosa Cambembe",
      specialty: "Terapeuta",
      email: "rosa.cambembe@gmail.com",
      address: "casa monte 900F",
      postalCode: "8150-031",
      isAdmin: false,
      isContractor: true,
      avatar: "f",
    },
  ],
};

// estes dados basta ter 6 fixos o resto é para incerir num input.
